module.exports=[
    {
        busOperatorId: '60d1ed8744a6f32acc7b1b5a', 
        departure: 'Bangalore',
        arrival: 'Chennai',
        ratings: 4.5,
        price: 1200,
        busType: 'acSleeper',
        amenities: ['WiFi', 'Blanket', 'Charging Point'],
        noOfRatings: 200,
        busPhotos: ['bus1.jpg', 'bus1-interior.jpg'],
        busPoints: ['Electronic City', 'Silk Board', 'Tambaram', 'Koyambedu']
    },
    {
        busOperatorId: '60d1ed8744a6f32acc7b1b5b',
        departure: 'Mumbai',
        arrival: 'Pune',
        ratings: 4.2,
        price: 800,
        busType: 'acSemiSleeper',
        amenities: ['WiFi', 'Charging Point'],
        noOfRatings: 150,
        busPhotos: ['bus2.jpg', 'bus2-interior.jpg'],
        busPoints: ['Borivali', 'Dadar', 'Wakad']
    },
    {
        busOperatorId: '60d1ed8744a6f32acc7b1b5c',
        departure: 'Delhi',
        arrival: 'Jaipur',
        ratings: 4.0,
        price: 1000,
        busType: 'nonAcSleeper',
        amenities: ['Blanket', 'Charging Point'],
        noOfRatings: 180,
        busPhotos: ['bus3.jpg', 'bus3-interior.jpg'],
        busPoints: ['ISBT Kashmiri Gate', 'Ajmeri Gate', 'Sindhi Camp']
    },
    {
        busOperatorId: '60d1ed8744a6f32acc7b1b5d',
        departure: 'Kolkata',
        arrival: 'Siliguri',
        ratings: 4.4,
        price: 1500,
        busType: 'nonAcSemiSleeper',
        amenities: ['WiFi', 'Blanket', 'Charging Point'],
        noOfRatings: 220,
        busPhotos: ['bus4.jpg', 'bus4-interior.jpg'],
        busPoints: ['Esplanade', 'Garia', 'Sevoke Road']
    },
    {
        busOperatorId: '60d1ed8744a6f32acc7b1b5e',
        departure: 'Hyderabad',
        arrival: 'Bangalore',
        ratings: 4.3,
        price: 1100,
        busType: 'acSleeper',
        amenities: ['WiFi', 'Blanket', 'Charging Point'],
        noOfRatings: 190,
        busPhotos: ['bus5.jpg', 'bus5-interior.jpg'],
        busPoints: ['Ameerpet', 'LB Nagar', 'Silk Board']
    },
    {
        busOperatorId: '60d1ed8744a6f32acc7b1b5f',
        departure: 'Chennai',
        arrival: 'Coimbatore',
        ratings: 4.6,
        price: 1300,
        busType: 'acSemiSleeper',
        amenities: ['WiFi', 'Charging Point'],
        noOfRatings: 210,
        busPhotos: ['bus6.jpg', 'bus6-interior.jpg'],
        busPoints: ['Koyambedu', 'Tambaram', 'Avarampalayam']
    },
    {
        busOperatorId: '60d1ed8744a6f32acc7b1b60',
        departure: 'Pune',
        arrival: 'Mumbai',
        ratings: 4.1,
        price: 750,
        busType: 'nonAcSleeper',
        amenities: ['Blanket', 'Charging Point'],
        noOfRatings: 160,
        busPhotos: ['bus7.jpg', 'bus7-interior.jpg'],
        busPoints: ['Wakad', 'Dadar', 'Borivali']
    },
    {
        busOperatorId: '60d1ed8744a6f32acc7b1b61',
        departure: 'Jaipur',
        arrival: 'Delhi',
        ratings: 4.0,
        price: 950,
        busType: 'nonAcSemiSleeper',
        amenities: ['WiFi', 'Charging Point'],
        noOfRatings: 175,
        busPhotos: ['bus8.jpg', 'bus8-interior.jpg'],
        busPoints: ['Sindhi Camp', 'Ajmeri Gate', 'ISBT Kashmiri Gate']
    },
    {
        busOperatorId: '60d1ed8744a6f32acc7b1b62',
        departure: 'Siliguri',
        arrival: 'Kolkata',
        ratings: 4.5,
        price: 1600,
        busType: 'acSleeper',
        amenities: ['WiFi', 'Blanket', 'Charging Point'],
        noOfRatings: 230,
        busPhotos: ['bus9.jpg', 'bus9-interior.jpg'],
        busPoints: ['Sevoke Road', 'Garia', 'Esplanade']
    },
    {
        busOperatorId: '60d1ed8744a6f32acc7b1b63',
        departure: 'Bangalore',
        arrival: 'Hyderabad',
        ratings: 4.4,
        price: 1150,
        busType: 'acSemiSleeper',
        amenities: ['WiFi', 'Charging Point'],
        noOfRatings: 195,
        busPhotos: ['bus10.jpg', 'bus10-interior.jpg'],
        busPoints: ['Silk Board', 'LB Nagar', 'Ameerpet']
    },
    {
        busOperatorId: '60d1ed8744a6f32acc7b1b64',
        departure: 'Coimbatore',
        arrival: 'Chennai',
        ratings: 4.7,
        price: 1350,
        busType: 'nonAcSleeper',
        amenities: ['Blanket', 'Charging Point'],
        noOfRatings: 225,
        busPhotos: ['bus11.jpg', 'bus11-interior.jpg'],
        busPoints: ['Avarampalayam', 'Tambaram', 'Koyambedu']
    },
    {
        busOperatorId: '60d1ed8744a6f32acc7b1b65',
        departure: 'Mumbai',
        arrival: 'Pune',
        ratings: 4.3,
        price: 820,
        busType: 'acSleeper',
        amenities: ['WiFi', 'Blanket', 'Charging Point'],
        noOfRatings: 170,
        busPhotos: ['bus12.jpg', 'bus12-interior.jpg'],
        busPoints: ['Dadar', 'Borivali', 'Wakad']
    },
    {
        busOperatorId: '60d1ed8744a6f32acc7b1b66',
        departure: 'Delhi',
        arrival: 'Jaipur',
        ratings: 4.1,
        price: 970,
        busType: 'acSemiSleeper',
        amenities: ['WiFi', 'Charging Point'],
        noOfRatings: 185,
        busPhotos: ['bus13.jpg', 'bus13-interior.jpg'],
        busPoints: ['Ajmeri Gate', 'Sindhi Camp', 'ISBT Kashmiri Gate']
    },
    {
        busOperatorId: '60d1ed8744a6f32acc7b1b67',
        departure: 'Kolkata',
        arrival: 'Siliguri',
        ratings: 4.6,
        price: 1550,
        busType: 'nonAcSleeper',
        amenities: ['Blanket', 'Charging Point'],
        noOfRatings: 240,
        busPhotos: ['bus14.jpg', 'bus14-interior.jpg'],
        busPoints: ['Garia', 'Sevoke Road', 'Esplanade']
    },
    {
        busOperatorId: '60d1ed8744a6f32acc7b1b68',
        departure: 'Hyderabad',
        arrival: 'Bangalore',
        ratings: 4.5,
        price: 1180,
        busType: 'nonAcSemiSleeper',
        amenities: ['WiFi', 'Charging Point'],
        noOfRatings: 205,
        busPhotos: ['bus15.jpg', 'bus15-interior.jpg'],
        busPoints: ['LB Nagar', 'Silk Board', 'Ameerpet']
    },
    {
        busOperatorId: '60d1ed8744a6f32acc7b1b69',
        departure: 'Chennai',
        arrival: 'Coimbatore',
        ratings: 4.8,
        price: 1380,
        busType: 'acSleeper',
        amenities: ['WiFi', 'Blanket', 'Charging Point'],
        noOfRatings: 235,
        busPhotos: ['bus16.jpg', 'bus16-interior.jpg'],
        busPoints: ['Tambaram', 'Avarampalayam', 'Koyam']
    }
]