module.exports=[
    { name: "Tamil Travels", gstId: "29AAACT1234A1Z5", ownerName: "Rajesh Kumar", email: "rajesh.tamiltravels@example.com", mobile: "9876543210", address: "Chennai, Tamil Nadu" },
    { name: "Madurai Bus Services", gstId: "29AAACT1235A1Z6", ownerName: "Arun Pandian", email: "arun.maduraibus@example.com", mobile: "9876543211", address: "Madurai, Tamil Nadu" },
    { name: "Coimbatore Express", gstId: "29AAACT1236A1Z7", ownerName: "Suresh Reddy", email: "suresh.coimbatoreexp@example.com", mobile: "9876543212", address: "Coimbatore, Tamil Nadu" },
    { name: "Kanyakumari Travels", gstId: "29AAACT1237A1Z8", ownerName: "Ravi Shankar", email: "ravi.kanyakumaritravels@example.com", mobile: "9876543213", address: "Kanyakumari, Tamil Nadu" },
    { name: "Trichy Tours", gstId: "29AAACT1238A1Z9", ownerName: "Vijay Anand", email: "vijay.trichytours@example.com", mobile: "9876543214", address: "Trichy, Tamil Nadu" },
    { name: "Salem Safar", gstId: "29AAACT1239A1ZA", ownerName: "Balaji Ramasamy", email: "balaji.salemsafar@example.com", mobile: "9876543215", address: "Salem, Tamil Nadu" },
    { name: "Tirunelveli Travels", gstId: "29AAACT1240A1ZB", ownerName: "Ganesh Kumar", email: "ganesh.tirunelvelitravels@example.com", mobile: "9876543216", address: "Tirunelveli, Tamil Nadu" },
    { name: "Erode Express", gstId: "29AAACT1241A1ZC", ownerName: "Mohan Raj", email: "mohan.erodeexp@example.com", mobile: "9876543217", address: "Erode, Tamil Nadu" },
    { name: "Tiruppur Travels", gstId: "29AAACT1242A1ZD", ownerName: "Hariharan Subramani", email: "hari.tiruppurtravels@example.com", mobile: "9876543218", address: "Tiruppur, Tamil Nadu" },
    { name: "Vellore Voyages", gstId: "29AAACT1243A1ZE", ownerName: "Prakash Rao", email: "prakash.vellorevoyages@example.com", mobile: "9876543219", address: "Vellore, Tamil Nadu" },
    { name: "Dharmapuri Deluxe", gstId: "29AAACT1244A1ZF", ownerName: "Sathish Kumar", email: "sathish.dharmapurideluxe@example.com", mobile: "9876543220", address: "Dharmapuri, Tamil Nadu" },
    { name: "Cuddalore Coaches", gstId: "29AAACT1245A1ZG", ownerName: "Natarajan R", email: "natarajan.cuddalorecoaches@example.com", mobile: "9876543221", address: "Cuddalore, Tamil Nadu" },
    { name: "Tuticorin Travels", gstId: "29AAACT1246A1ZH", ownerName: "Muthuvel Karunanidhi", email: "muthu.tuticorintravels@example.com", mobile: "9876543222", address: "Tuticorin, Tamil Nadu" },
    { name: "Nagapattinam Buses", gstId: "29AAACT1247A1ZI", ownerName: "Saravanan R", email: "saravanan.nagapattinambuses@example.com", mobile: "9876543223", address: "Nagapattinam, Tamil Nadu" },
    { name: "Villupuram Travels", gstId: "29AAACT1248A1ZJ", ownerName: "Karthik P", email: "karthik.villupuramtravels@example.com", mobile: "9876543224", address: "Villupuram, Tamil Nadu" },
    { name: "Thanjavur Transport", gstId: "29AAACT1249A1ZK", ownerName: "Subramaniam V", email: "subramaniam.thanjavurtransport@example.com", mobile: "9876543225", address: "Thanjavur, Tamil Nadu" },
    { name: "Krishnagiri Coaches", gstId: "29AAACT1250A1ZL", ownerName: "Ramesh Babu", email: "ramesh.krishnagiricoaches@example.com", mobile: "9876543226", address: "Krishnagiri, Tamil Nadu" },
    { name: "Theni Travels", gstId: "29AAACT1251A1ZM", ownerName: "Murugan S", email: "murugan.thenitravels@example.com", mobile: "9876543227", address: "Theni, Tamil Nadu" },
    { name: "Kanchipuram Express", gstId: "29AAACT1252A1ZN", ownerName: "Gopinath K", email: "gopinath.kanchipuramexp@example.com", mobile: "9876543228", address: "Kanchipuram, Tamil Nadu" },
    { name: "Karur Transport", gstId: "29AAACT1253A1ZO", ownerName: "Srinivasan R", email: "srinivasan.karurtransport@example.com", mobile: "9876543229", address: "Karur, Tamil Nadu" },
    { name: "Namakkal Natives", gstId: "29AAACT1254A1ZP", ownerName: "Anand B", email: "anand.namakkalnatives@example.com", mobile: "9876543230", address: "Namakkal, Tamil Nadu" },
    { name: "Perambalur Pilgrims", gstId: "29AAACT1255A1ZQ", ownerName: "Balasubramanian V", email: "balasubramanian.perambalupilgrims@example.com", mobile: "9876543231", address: "Perambalur, Tamil Nadu" },
    { name: "Pudukkottai Travels", gstId: "29AAACT1256A1ZR", ownerName: "Sivakumar R", email: "sivakumar.pudukkottaitravels@example.com", mobile: "9876543232", address: "Pudukkottai, Tamil Nadu" },
    { name: "Ramanathapuram Rides", gstId: "29AAACT1257A1ZS", ownerName: "Dinesh K", email: "dinesh.ramanathapuramrides@example.com", mobile: "9876543233", address: "Ramanathapuram, Tamil Nadu" },
    { name: "Sivaganga Safaris", gstId: "29AAACT1258A1ZT", ownerName: "Senthil Kumar", email: "senthil.sivagangasafaris@example.com", mobile: "9876543234", address: "Sivaganga, Tamil Nadu" },
    { name: "Virudhunagar Ventures", gstId: "29AAACT1259A1ZU", ownerName: "Ganesan P", email: "ganesan.virudhunagarventures@example.com", mobile: "9876543235", address: "Virudhunagar, Tamil Nadu" },
    { name: "Dindigul Deluxe", gstId: "29AAACT1260A1ZV", ownerName: "Rajasekar K", email: "rajasekar.dindiguldeluxe@example.com", mobile: "9876543236", address: "Dindigul, Tamil Nadu" },
    { name: "Thiruvarur Travels", gstId: "29AAACT1261A1ZW", ownerName: "Sankar P", email: "sankar.thiruvarurtravels@example.com", mobile: "9876543237", address: "Thiruvarur, Tamil Nadu" },
    { name: "Thoothukudi Tours", gstId: "29AAACT1262A1ZX", ownerName: "Pradeep K", email: "pradeep.thoothukuditours@example.com", mobile: "9876543238", address: "Thoothukudi, Tamil Nadu" },
    { name: "Nagercoil Natives", gstId: "29AAACT1263A1ZY", ownerName: "Kannan R", email: "kannan.nagercoilnatives@example.com", mobile: "9876543239", address: "Nagercoil, Tamil Nadu" },
]